# Generated by Django 5.1.2 on 2024-11-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'permissions': [('advance pro', 'Advance Pro Perm'), ('advance', 'Advance Perm'), ('basic', 'Basic Perm'), ('free', 'Free Perm')],
            },
        ),
    ]
