# Generated by Django 5.1.2 on 2024-11-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcription',
            name='group',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
