# Generated by Django 5.1.2 on 2024-11-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subcription_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
